---
- name: Install and configure Climate Control Service
  hosts: localhost
  become: true

  vars_files:
    - ../../services/climate_control/climate_control_config.yml

  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - python3-venv
          - python3-pip
        state: present

    - name: Create a Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /usr/local/bin/climate_control_venv
        creates: /usr/local/bin/climate_control_venv/bin/activate

    - name: Install required Python packages in the virtual environment
      ansible.builtin.command:
        cmd: |
          /usr/local/bin/climate_control_venv/bin/pip install \
          paho-mqtt \
          tapo \
          pyyaml

    - name: Copy the climate control script to the destination
      ansible.builtin.copy:
        src: ../../services/climate_control/climate_control.py
        dest: /usr/local/bin/climate_control.py
        mode: '0755'

    - name: Copy the MQTT configuration file
      ansible.builtin.copy:
        src: ../../services/climate_control/mqtt_config.yml
        dest: /usr/local/bin/mqtt_config.yml
        mode: '0644'

    - name: Create systemd service file for the Climate Control script
      ansible.builtin.template:
        src: templates/climate_control_service.j2
        dest: /etc/systemd/system/climate_control_service.service
        mode: '0644'

    - name: Reload systemd to pick up the new service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start the Climate Control Service
      ansible.builtin.systemd:
        name: climate_control_service
        enabled: true
        state: started
