---
- name: Install and configure DHT Sensor Service
  hosts: localhost
  become: true

  vars_files:
    - ../../services/dht_sensor/dht_sensor_config.yml

  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - python3-venv
          - python3-pip
        state: present

    - name: Create a Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /usr/local/bin/dht_sensor_venv
        creates: /usr/local/bin/dht_sensor_venv/bin/activate

    - name: Install required Python packages in the virtual environment
      ansible.builtin.command:
        cmd: |
          /usr/local/bin/dht_sensor_venv/bin/pip install \
          pyyaml \
          tapo \
          Adafruit_DHT

    - name: Copy the climate control script to the destination
      ansible.builtin.copy:
        src: ../../services/dht_sensor/dht_sensor.py
        dest: /usr/local/bin/dht_sensor.py
        mode: '0755'

    - name: Copy the MQTT configuration file
      ansible.builtin.copy:
        src: ../../services/dht_sensor/dht_sensor_config.yml
        dest: /usr/local/bin/dht_sensor_config.yml
        mode: '0644'

    - name: Ensure /var/log/dht_sensor.log exists
      ansible.builtin.command:
        cmd: touch /var/log/dht_sensor.log
        creates: /var/log/dht_sensor.log

    - name: Set correct permissions on /var/log/dht_sensor.log
      ansible.builtin.file:
        path: /var/log/dht_sensor.log
        owner: pingu
        group: pingu
        mode: '0644'

    - name: Create systemd service file for the DHT script
      ansible.builtin.template:
        src: dht_sensor_service.j2
        dest: /etc/systemd/system/dht_sensor_service.service
        mode: '0644'

    - name: Reload systemd to pick up the new service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start the DHT Service
      ansible.builtin.systemd:
        name: dht_sensor_service
        enabled: true
        state: started
