---
- name: Install and configure all services
  hosts: localhost
  become: true

- name: Install MQTT Broker
  import_playbook: install_mqtt.yml

- name: Install Climate Control Service
  import_playbook: install_climate_control.yml

- name: Install DHT Sensor Service
  import_playbook: install_dht_sensor.yml
