mqtt:
  broker_host: "localhost"
  broker_port: 1883
  topics:
    humidity_topic: "sensors/humidity/#"
    temperature_topic: "sensors/temperature/#"
  ranges:
    humidity: [60, 100]  # Example range: 30% to 50%
    temperature: [25, 100]  # Example range: 20°C to 25°C
